---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.sregym-controller.io
  resources:
  - sregymexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sregym-controller.io
  resources:
  - sregymexperiments/finalizers
  verbs:
  - update
- apiGroups:
  - batch.sregym-controller.io
  resources:
  - sregymexperiments/status
  verbs:
  - get
  - patch
  - update
